### ISSUE TITLE
[Feature Request] Train-Case support

### ISSUE THREAD

**Issue by another-guy** [vad3x/case-extensions#1]
Hello Vadim

First of all thanks a ton for a nice package! I am surprised I was unable to find any alternatives to your NuGet package which was first released in April last year. Good job!

I have a couple of questions. Hopefully, you will not be mad if I don't open an issue per question. 

* Are there any plans to support Train-Case? This would make the library a little more complete, IMO. By the way, the style is referred here http://stackoverflow.com/a/17820138/482868

* Are there plans to support `netstandard1.6`? The compilation fails for one of the projects I'd like to introduce a dependency on CaseExtensions.

```
error: Package CaseExtensions 1.0.1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package CaseExtensions 1.0.1 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
error: One or more packages are incompatible with .NETStandard,Version=v1.6.
```

* You may want to change wording in the documentation to clarify that cross-style translations are possible (i.e. kebab to camel, or camel to snake). It might be obvious from the word any in this sentence (but it was not for me)
> The library that allows to change any string case to PascalCase/camelCase/kebab-case/snake_case.

So, I had to depend on CaseExtensions 1.0.1 and run some test code (funny that I did not notice the unit tests in the repo).

-- Igor

**Comment by vad3x** [comment]
Hi Igor!

Thanks for your interest for the project. I've started it as an experiment with dotnet core many months ago, and forgot about this :). That's why there is only one version of it.

> Are there any plans to support Train-Case?
> Are there plans to support netstandard1.6?

Sure, I will update the package as soon as possible.

> You may want to change wording in the documentation ...

You are welcome to make a PR with the changes :)

Thanks again!

**Comment by vad3x** [comment]
Done

**Comment by another-guy** [comment]
Thanks for the quick update!

I opened a PR #2 for doc changes. I am not sure whether you want to see that many examples or not -- feel free to reject or suggest a change to the PR.
I can see how the amount of examples will grow exponentially if more `.ToXyz()` translations are added. On another hand, I can't anticipate new styles coming any time soon...

**Comment by vad3x** [comment]
Think you!
Let's do it this way by now.
